import express from 'express';
import Order from '../models/Order.js';
import Item from '../models/Item.js';

const router = express.Router();

// Get all orders
router.get('/', async (req, res) => {
    try {
        const orders = await Order.find().sort({ createdAt: -1 });
        res.json(orders);
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
});

// Create an order
router.post('/', async (req, res) => {
    console.log('Received order data:', {
        customerName: req.body.customerDetails?.fullName,
        itemCount: req.body.items?.length
    });

    const session = await Item.startSession();
    session.startTransaction();

    try {
        // Check availability and decrement stock
        for (const item of req.body.items) {
            const stockItem = await Item.findById(item.id).session(session);
            if (!stockItem) {
                throw new Error(`Item not found: ${item.designNo}`);
            }
            if (stockItem.pcs < item.quantity) {
                throw new Error(`Insufficient stock for item: ${item.designNo}. Available: ${stockItem.pcs}`);
            }
            stockItem.pcs -= item.quantity;
            await stockItem.save({ session });
        }

        const order = new Order(req.body);
        const newOrder = await order.save({ session });

        await session.commitTransaction();
        console.log('Order saved successfully:', newOrder._id);
        res.status(201).json(newOrder);
    } catch (error) {
        await session.abortTransaction();
        console.error('Error saving order:', error.message);
        res.status(400).json({ message: error.message });
    } finally {
        session.endSession();
    }
});

// Update order status or tracking notes
router.put('/:id', async (req, res) => {
    const session = await Item.startSession();
    session.startTransaction();

    try {
        const { status, modifiedBy, trackingNote } = req.body;
        const updateData = { ...req.body };
        const order = await Order.findById(req.params.id).session(session);

        if (!order) {
            throw new Error('Order not found');
        }

        // Handle Cancellation - Restore Stock
        if (status === 'Cancelled' && order.status !== 'Cancelled') {
            for (const item of order.items) {
                const stockItem = await Item.findById(item.id).session(session);
                if (stockItem) {
                    stockItem.pcs += item.quantity;
                    await stockItem.save({ session });
                }
            }
        }

        // If un-cancelling (unlikely but safe to handle), deduct stock again
        if (order.status === 'Cancelled' && status && status !== 'Cancelled') {
            for (const item of order.items) {
                const stockItem = await Item.findById(item.id).session(session);
                if (stockItem) {
                    if (stockItem.pcs < item.quantity) {
                        throw new Error(`Cannot re-activate order. Insufficient stock for ${item.designNo}`);
                    }
                    stockItem.pcs -= item.quantity;
                    await stockItem.save({ session });
                }
            }
        }

        // If this is a status update, append to statusHistory and add a tracking note
        if (status && order.status !== status) {
            // Add to status history
            updateData.$push = updateData.$push || {};
            updateData.$push.statusHistory = {
                status,
                timestamp: new Date()
            };

            // Add auto-generated tracking note
            const noteMessage = `Status updated to ${status} by ${modifiedBy || 'System'}`;
            // Use existing structure update
            if (!updateData.$push.trackingNotes) updateData.$push.trackingNotes = {};
            // This structure was slightly simplified in my head, let's match the original style more closely or clean it up
            // Re-using the logic from before but careful with $push multiple fields
            updateData.$push = {
                ...(updateData.$push || {}),
                trackingNotes: {
                    id: `note-${Date.now()}`,
                    message: trackingNote || noteMessage,
                    timestamp: new Date(),
                    isAutoGenerated: true
                }
            };
        } else if (trackingNote) {
            // Handle manual note addition if sent via this route
            updateData.$push = updateData.$push || {};
            updateData.$push.trackingNotes = {
                id: `note-${Date.now()}`,
                message: trackingNote,
                timestamp: new Date(),
                isAutoGenerated: false
            };
        }

        // We use findByIdAndUpdate usually, but with session we need to be careful.
        // Mongoose findByIdAndUpdate doesn't support session in options passed as 3rd arg easily in all versions? 
        // Actually it does. let's use it.

        const updatedOrder = await Order.findByIdAndUpdate(
            req.params.id,
            updateData,
            { new: true, session }
        );

        await session.commitTransaction();
        res.json(updatedOrder);
    } catch (error) {
        await session.abortTransaction();
        console.error('Error updating order:', error);
        res.status(400).json({ message: error.message });
    } finally {
        session.endSession();
    }
});

// Delete an order
router.delete('/:id', async (req, res) => {
    const session = await Item.startSession();
    session.startTransaction();
    try {
        const order = await Order.findById(req.params.id).session(session);
        if (order) {
            // If deleting a non-cancelled, non-delivered (?) order, should we restore stock?
            // "Maintain stock based on order checkout, delivery and cancellation"
            // If I delete a PENDING order, I should definitely restore stock.
            // If I delete a DELIVERED order, I should NOT restore stock (item is gone).
            // If I delete a CANCELLED order, stock was already restored when it was cancelled.

            if (order.status !== 'Cancelled' && order.status !== 'Delivered') {
                for (const item of order.items) {
                    const stockItem = await Item.findById(item.id).session(session);
                    if (stockItem) {
                        stockItem.pcs += item.quantity;
                        await stockItem.save({ session });
                    }
                }
            }
            await Order.findByIdAndDelete(req.params.id).session(session);
        }
        await session.commitTransaction();
        res.json({ message: 'Order deleted' });
    } catch (error) {
        await session.abortTransaction();
        res.status(500).json({ message: error.message });
    } finally {
        session.endSession();
    }
});

export default router;
