import React, { useState } from 'react';
import type { TrackingNote } from '../types/Order';

interface OrderTrackingNotesProps {
    notes: TrackingNote[];
    onAddNote: (message: string) => void;
}

const OrderTrackingNotes: React.FC<OrderTrackingNotesProps> = ({ notes, onAddNote }) => {
    const [newNote, setNewNote] = useState('');

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        if (newNote.trim()) {
            onAddNote(newNote.trim());
            setNewNote('');
        }
    };

    const formatDate = (date: Date): string => {
        return new Intl.DateTimeFormat('en-IN', {
            day: 'numeric',
            month: 'short',
            year: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
        }).format(new Date(date));
    };

    // Sort notes by timestamp (newest first)
    const sortedNotes = [...notes].sort(
        (a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()
    );

    return (
        <div className="py-6 border-t border-white/10">
            <h3 className="text-lg font-semibold text-white mb-4">Tracking Notes</h3>

            {/* Add Note Form */}
            <form onSubmit={handleSubmit} className="mb-6">
                <div className="flex gap-2">
                    <input
                        type="text"
                        value={newNote}
                        onChange={(e) => setNewNote(e.target.value)}
                        placeholder="Add a tracking note..."
                        className="flex-1 px-4 py-2.5 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-gold-500/50 focus:border-gold-500/50 transition-all"
                    />
                    <button
                        type="submit"
                        disabled={!newNote.trim()}
                        className="px-6 py-2.5 bg-gradient-gold text-white font-semibold rounded-lg hover:shadow-lg hover:shadow-gold-500/30 transition-all duration-300 hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100"
                    >
                        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                        </svg>
                    </button>
                </div>
            </form>

            {/* Notes List */}
            <div className="space-y-3 max-h-96 overflow-y-auto pr-2 custom-scrollbar">
                {sortedNotes.length === 0 ? (
                    <div className="text-center py-12">
                        <div className="w-16 h-16 bg-white/5 rounded-full flex items-center justify-center mx-auto mb-4">
                            <svg className="w-8 h-8 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                            </svg>
                        </div>
                        <p className="text-gray-500 font-medium">No tracking notes yet</p>
                        <p className="text-gray-600 text-sm mt-1">Add your first note above to track this order</p>
                    </div>
                ) : (
                    sortedNotes.map((note, index) => (
                        <div
                            key={note.id}
                            className={`p-4 rounded-lg border transition-all duration-300 hover:scale-[1.02] animate-fade-in ${note.isAutoGenerated
                                    ? 'bg-gold-500/5 border-gold-500/20 hover:border-gold-500/30'
                                    : 'bg-white/5 border-white/10 hover:border-white/20'
                                }`}
                            style={{
                                animationDelay: `${index * 50}ms`
                            }}
                        >
                            <div className="flex items-start justify-between gap-3">
                                <div className="flex-1 flex items-start gap-3">
                                    {note.isAutoGenerated ? (
                                        <div className="flex-shrink-0 w-6 h-6 rounded-full bg-gold-500/20 flex items-center justify-center mt-0.5">
                                            <svg className="w-3.5 h-3.5 text-gold-500" fill="currentColor" viewBox="0 0 20 20">
                                                <path fillRule="evenodd" d="M11.3 1.046A1 1 0 0112 2v5h4a1 1 0 01.82 1.573l-7 10A1 1 0 018 18v-5H4a1 1 0 01-.82-1.573l7-10a1 1 0 011.12-.38z" clipRule="evenodd" />
                                            </svg>
                                        </div>
                                    ) : (
                                        <div className="flex-shrink-0 w-6 h-6 rounded-full bg-white/10 flex items-center justify-center mt-0.5">
                                            <svg className="w-3.5 h-3.5 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                                                <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                                            </svg>
                                        </div>
                                    )}
                                    <p className="text-white text-sm leading-relaxed flex-1">
                                        {note.message}
                                    </p>
                                </div>
                                {note.isAutoGenerated && (
                                    <span className="flex-shrink-0 px-2 py-0.5 text-[10px] bg-gold-500/20 text-gold-500 rounded-full border border-gold-500/30 font-semibold">
                                        AUTO
                                    </span>
                                )}
                            </div>
                            <div className="flex items-center gap-2 mt-2 ml-9">
                                <svg className="w-3 h-3 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                                </svg>
                                <p className="text-xs text-gray-500">
                                    {formatDate(note.timestamp)}
                                </p>
                            </div>
                        </div>
                    ))
                )}
            </div>
        </div>
    );
};

export default OrderTrackingNotes;
