import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';
import type { Order, OrderStatus, CustomerDetails } from '../types/Order';
import api from '../api/axios';

interface CartItem {
    id: string;
    designNo: string;
    category: string;
    imageUrl?: string;
    quantity: number;
    size?: number;
}

interface OrderContextType {
    orders: Order[];
    createOrder: (customerDetails: CustomerDetails, items: CartItem[]) => Promise<void>;
    updateOrderStatus: (orderId: string, status: OrderStatus, modifiedBy?: string) => Promise<void>;
    addTrackingNote: (orderId: string, note: string) => Promise<void>;
    deleteOrder: (orderId: string) => Promise<void>;
}

const OrderContext = createContext<OrderContextType | undefined>(undefined);

// Hook for using the Order context
export const useOrders = () => {
    const context = useContext(OrderContext);
    if (context === undefined) {
        throw new Error('useOrders must be used within an OrderProvider');
    }
    return context;
};

// Main Provider Component
export function OrderProvider({ children }: { children: ReactNode }) {
    const [orders, setOrders] = useState<Order[]>([]);

    const fetchOrders = async () => {
        try {
            const response = await api.get('orders');
            const normalizedOrders = response.data.map((order: any) => ({
                ...order,
                id: order._id || order.id,
                createdAt: new Date(order.createdAt),
                updatedAt: new Date(order.updatedAt),
                statusHistory: order.statusHistory.map((h: any) => ({
                    ...h,
                    timestamp: new Date(h.timestamp)
                })),
                trackingNotes: order.trackingNotes.map((n: any) => ({
                    ...n,
                    timestamp: new Date(n.timestamp)
                }))
            }));
            setOrders(normalizedOrders);
        } catch (error) {
            console.error('Failed to fetch orders:', error);
        }
    };

    useEffect(() => {
        fetchOrders();
    }, []);

    const createOrder = async (customerDetails: CustomerDetails, items: any[]) => {
        const orderItems = items.map(item => ({
            id: item.id,
            designNo: item.designNo,
            category: item.category,
            quantity: item.quantity || 1,
            size: item.size,
            imageUrl: item.imageUrl,
        }));

        // totalAmount removed

        const newOrder = {
            customerDetails,
            items: orderItems,
            status: 'Pending' as OrderStatus,
            statusHistory: [{ status: 'Pending' as OrderStatus, timestamp: new Date() }],
            trackingNotes: [{
                id: `note-${Date.now()}`,
                message: 'Order created',
                timestamp: new Date(),
                isAutoGenerated: true,
            }],
        };

        try {
            console.log('Creating order:', { customerName: customerDetails.fullName, itemCount: orderItems.length });
            const response = await api.post('orders', newOrder);
            console.log('Order created successfully:', response.data._id);

            // Add the new order to state immediately for instant UI update
            const createdOrder = {
                ...response.data,
                id: response.data._id || response.data.id,
                createdAt: new Date(response.data.createdAt),
                updatedAt: new Date(response.data.updatedAt),
                statusHistory: response.data.statusHistory.map((h: any) => ({
                    ...h,
                    timestamp: new Date(h.timestamp)
                })),
                trackingNotes: response.data.trackingNotes.map((n: any) => ({
                    ...n,
                    timestamp: new Date(n.timestamp)
                }))
            };
            setOrders(prevOrders => [createdOrder, ...prevOrders]);
        } catch (error: any) {
            console.error('Failed to create order:', error);
            const errorMessage = error.response?.data?.message || error.message || 'Failed to create order';
            throw new Error(errorMessage);
        }
    };

    const updateOrderStatus = async (orderId: string, newStatus: OrderStatus, modifiedBy?: string) => {
        try {
            console.log(`Updating order ${orderId} status to ${newStatus} by ${modifiedBy}`);
            const response = await api.put(`orders/${orderId}`, {
                status: newStatus,
                modifiedBy
            });

            // Update local state with the returned updated order from backend
            const updatedOrder = {
                ...response.data,
                id: response.data._id || response.data.id,
                createdAt: new Date(response.data.createdAt),
                updatedAt: new Date(response.data.updatedAt),
                statusHistory: response.data.statusHistory.map((h: any) => ({
                    ...h,
                    timestamp: new Date(h.timestamp)
                })),
                trackingNotes: response.data.trackingNotes.map((n: any) => ({
                    ...n,
                    timestamp: new Date(n.timestamp)
                }))
            };

            setOrders(prevOrders => prevOrders.map(o =>
                o.id === orderId ? updatedOrder : o
            ));
        } catch (error) {
            console.error('Failed to update order status:', error);
            throw error;
        }
    };

    const addTrackingNote = async (orderId: string, message: string) => {
        const order = orders.find(o => o.id === orderId);
        if (!order) return;

        const updatedData = {
            trackingNotes: [
                ...order.trackingNotes,
                {
                    id: `note-${Date.now()}`,
                    message,
                    isAutoGenerated: false,
                },
            ],
        };

        try {
            await api.put(`orders/${orderId}`, updatedData);
            await fetchOrders();
        } catch (error) {
            console.error('Failed to add tracking note:', error);
        }
    };

    const deleteOrder = async (orderId: string) => {
        try {
            await api.delete(`orders/${orderId}`);
            await fetchOrders();
        } catch (error) {
            console.error('Failed to delete order:', error);
        }
    };

    return (
        <OrderContext.Provider value={{ orders, createOrder, updateOrderStatus, addTrackingNote, deleteOrder }}>
            {children}
        </OrderContext.Provider>
    );
}
