export type OrderStatus = 'Pending' | 'Processing' | 'Shipped' | 'Delivered' | 'Cancelled';

export interface StatusHistory {
    status: OrderStatus;
    timestamp: Date;
}

export interface TrackingNote {
    id: string;
    message: string;
    timestamp: Date;
    isAutoGenerated: boolean; // true for status changes, false for manual notes
}

export interface CustomerDetails {
    fullName: string;
    name?: string; // For backward compatibility
    email: string;
    phone: string;
    address: string;
}

export interface OrderItem {
    id: string;
    designNo: string;
    category: string;
    quantity: number;
    size?: number;
    imageUrl?: string;
}

export interface Order {
    id: string;
    customerDetails: CustomerDetails;
    items: OrderItem[];
    status: OrderStatus;
    statusHistory: StatusHistory[];
    trackingNotes: TrackingNote[];
    createdAt: Date;
    updatedAt: Date;
}
