import mongoose from 'mongoose';

const orderSchema = new mongoose.Schema({
    customerDetails: {
        fullName: { type: String, required: true },
        email: { type: String, required: true },
        phone: { type: String, required: true },
        address: { type: String, required: true },
    },
    items: [{
        id: { type: String, required: true },
        designNo: { type: String, required: true },
        category: { type: String, required: true },
        quantity: { type: Number, required: true },
        size: { type: Object }, // Allow size to be stored
        imageUrl: { type: String },
    }],
    status: { type: String, default: 'Pending' },
    statusHistory: [{
        status: { type: String, required: true },
        timestamp: { type: Date, default: Date.now },
    }],
    trackingNotes: [{
        id: { type: String, required: true },
        message: { type: String, required: true },
        timestamp: { type: Date, default: Date.now },
        isAutoGenerated: { type: Boolean, default: false },
    }],
}, { timestamps: true });

const Order = mongoose.model('Order', orderSchema);
export default Order;
